version: '3'
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: whatzasDev
      POSTGRES_PASSWORD: password
      TZ: "America/Sao_Paulo"
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/dataWhatzap